'use client'

import { useEffect, useState } from 'react'
import { motion, useReducedMotion } from 'motion/react'
import { ArrowUpRight, ChevronDown, GitBranch, Mail, Menu, X } from 'lucide-react'

const projects = [
  { id: '01', name: 'Lura Law', type: 'LEGALTECH / SAAS / CLOUD', role: 'Full Stack & DevOps', description: 'A LegalTech platform for lawyers and law firms, combining case management, documents, AI-assisted workflows, OCR and asynchronous processing.', stack: ['Next.js', 'NestJS', 'PostgreSQL', 'Prisma', 'Redis', 'BullMQ', 'Docker', 'Terraform', 'Azure', 'AKS', 'Kubernetes', 'Prometheus', 'Grafana'] },
  { id: '02', name: 'B-Smart Travel', type: 'B2B TRAVEL TECHNOLOGY', role: 'Full Stack & DevOps Intern', description: 'A B2B platform for managing and distributing travel services with real-time booking workflows.', stack: ['React', 'Node.js', 'Docker', 'CI/CD', 'REST APIs', 'Real-time'] },
  { id: '03', name: 'Comunik CRM', type: 'CRM / REAL-TIME WEB APP', role: 'Full Stack Intern', description: 'Customer management, dashboards and live operational data connected through WebSockets.', stack: ['React', 'Node.js', 'WebSockets', 'Tailwind'] },
  { id: '04', name: 'Vermeg', type: 'ENTERPRISE ENGINEERING', role: 'Full Stack & DevOps Intern', description: 'Enterprise application delivery across Spring Boot, Azure, CI/CD, Keycloak and role-based access control.', stack: ['Spring Boot', 'Azure', 'CI/CD', 'Keycloak', 'RBAC'] },
]
const experience = [['2026', 'LURA LAW', 'Full Stack & DevOps Intern', 'February 2026 — July 2026', 'Next.js · NestJS · Azure · AKS · Terraform · Kubernetes'], ['2025', 'B-SMART TRAVEL', 'Full Stack & DevOps Intern', 'February 2025 — November 2025', 'React · Node.js · Docker · CI/CD'], ['2024', 'COMUNIK CRM', 'Full Stack Intern', 'June 2024 — August 2024', 'React · Node.js · WebSockets · TailwindCSS'], ['2023', 'VERMEG', 'Full Stack & DevOps Intern', 'January 2023 — June 2023', 'Spring Boot · Azure · CI/CD · Keycloak']]
const expertise = { 'FULL STACK': ['React', 'Next.js', 'Angular', 'Vue', 'NestJS', 'Node.js', 'Spring Boot', 'Laravel'], 'BACKEND & DATA': ['PostgreSQL', 'Prisma', 'MongoDB', 'MySQL', 'Oracle', 'Redis', 'BullMQ'], 'CLOUD & DEVOPS': ['Docker', 'Kubernetes', 'Helm', 'Terraform', 'Azure', 'AKS', 'DigitalOcean', 'GitHub Actions', 'Jenkins', 'GitLab CI'], 'OBSERVABILITY & SYSTEMS': ['Nginx', 'Traefik', 'Prometheus', 'Grafana', 'RAG', 'OCR', 'Async processing', 'REST APIs', 'WebSockets'] }
const pipeline = [['01', 'CODE', 'Source and product decisions'], ['02', 'CI', 'Checks, tests and repeatable builds'], ['03', 'DOCKER', 'Containerized application workloads'], ['04', 'GHCR', 'Versioned image registry'], ['05', 'AKS', 'Kubernetes orchestration'], ['06', 'OBSERVE', 'Metrics, logs and feedback']]

function Signal({ className = '' }: { className?: string }) { return <span className={`signal-line ${className}`} aria-hidden="true"><i /></span> }
function Reveal({ children, className = '', delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { const reduced = useReducedMotion(); return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 18 }} whileInView={reduced ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ duration: .65, delay }}>{children}</motion.div> }
function Screenshot({ name, large = false }: { name: string; large?: boolean }) { return <div className={`screenshot-slot ${large ? 'screenshot-large' : ''}`} aria-label={`${name} screenshot slot`}><span>IMAGE SLOT</span><b>{name}</b><small>/public/projects/{name.toLowerCase().replaceAll(' ', '-')}/</small><Signal /></div> }
function Architecture() { const [active, setActive] = useState(-1); const nodes = ['Users', 'Next.js', 'NestJS API', 'BullMQ workers', 'PostgreSQL · Redis', 'Azure / AKS']; return <div className="architecture"><div className="diagram-caption">LURA LAW / SYSTEM MAP <span>01—06</span></div><div className="diagram-flow">{nodes.map((item, i) => <button className={`diagram-node ${active === i ? 'is-active' : ''} ${active > -1 && active !== i ? 'is-quiet' : ''}`} key={item} onMouseEnter={() => setActive(i)} onFocus={() => setActive(i)} onMouseLeave={() => setActive(-1)} onBlur={() => setActive(-1)}><span>0{i + 1}</span><b>{item}</b><small>{['Product surface', 'Frontend', 'Domain services', 'OCR · AI · documents', 'Persistence + queue', 'Runtime platform'][i]}</small></button>)}</div></div> }
function SystemCursor() { const reduced = useReducedMotion(); useEffect(() => { if (reduced || window.matchMedia('(pointer: coarse)').matches) return; const move = (event: MouseEvent) => document.documentElement.style.setProperty('--cursor-x', `${event.clientX}px`); const moveY = (event: MouseEvent) => document.documentElement.style.setProperty('--cursor-y', `${event.clientY}px`); window.addEventListener('mousemove', move); window.addEventListener('mousemove', moveY); return () => { window.removeEventListener('mousemove', move); window.removeEventListener('mousemove', moveY) } }, [reduced]); return <span className="system-cursor" aria-hidden="true" /> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false); const [open, setOpen] = useState(0); const [expertiseTab, setExpertiseTab] = useState<keyof typeof expertise>('FULL STACK'); const [activeSection, setActiveSection] = useState('01');
  useEffect(() => { const sections = [...document.querySelectorAll('section[id]')]; const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && setActiveSection(`${Math.min(5, sections.findIndex(s => s.id === entry.target.id) + 1}`.padStart(2, '0'))), { rootMargin: '-35% 0px -55% 0px' }); sections.forEach(section => observer.observe(section)); return () => observer.disconnect() }, []);
  return <main id="top"><SystemCursor /><div className="section-progress" aria-label="Page sections"><span>{activeSection}</span><div>{['01', '02', '03', '04', '05'].map(n => <i key={n} className={activeSection === n ? 'active' : ''} />)}</div></div>
    <header className="site-header"><a href="#top" className="brand"><strong>WA</strong><span>WAJDI AMDOUNI<small>SOFTWARE ENGINEER</small></span></a><nav className={menuOpen ? 'nav-open' : ''}>{[['WORK', 'work'], ['STACK', 'stack'], ['EXPERIENCE', 'experience'], ['ABOUT', 'about']].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><a className="header-resume" href="mailto:amdouniwajdiii@gmail.com">RESUME <ArrowUpRight /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></header>
    <section className="hero section-shell"><div className="hero-copy"><p className="eyebrow"><i /> SYSTEM ONLINE <span className="status-note">/ AVAILABLE FOR OPPORTUNITIES</span></p><p className="overline">FULL STACK DEVELOPER <span>×</span> CLOUD & DEVOPS ENTHUSIAST</p><h1>Wajdi<br /><em>Amdouni.</em></h1><p className="hero-intro">Software engineer building production-oriented web applications, backend systems and cloud infrastructure.</p><div className="hero-links"><a className="button button-primary" href="#work">VIEW PROJECTS <ArrowUpRight /></a><a className="button" href="mailto:amdouniwajdiii@gmail.com">CONTACT <Mail /></a></div></div><div className="hero-system"><div className="portrait-frame"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/profile%20pic-LEPjak6LmAvDnqfpP1Zp0O4vlNcJ7s.jpg" alt="Portrait of Wajdi Amdouni" /><span>WA / 2026</span><Signal /></div><div className="hero-meta"><span>BASED IN</span><b>TUNISIA</b><span>FOCUS</span><b>PRODUCT → PLATFORM</b></div><div className="mini-pipeline"><span>CODE</span><i>↓</i><span>BUILD</span><i>↓</i><span>DEPLOY</span><i>↓</i><span>OBSERVE</span></div></div><div className="hero-footer"><span>SCROLL TO EXPLORE</span><span>01 / INTRODUCTION</span><span>FULL STACK · CLOUD · DEVOPS</span></div></section>
    <Reveal><section id="work" className="section section-shell"><div className="section-intro"><span className="section-no">01</span><div><p className="eyebrow">SELECTED WORK</p><h2>Products with<br /><em>systems behind them.</em></h2></div><p>Real product work across full-stack development, backend systems, cloud infrastructure and delivery automation.</p></div><article className="featured"><div className="featured-visual"><Screenshot name="Lura Law" large /><Architecture /></div><div className="project-info"><p className="project-type">{projects[0].type}</p><h3>{projects[0].name}</h3><p>{projects[0].description}</p><div className="project-meta"><span>ROLE<b>{projects[0].role}</b></span><span>STATUS<b>FEATURED CASE STUDY</b></span></div><div className="tags">{projects[0].stack.map(x => <span key={x}>{x}</span>)}</div><a className="text-button" href="#lura-case">VIEW ENGINEERING NOTES <ArrowUpRight /></a></div></article><div className="project-list">{projects.slice(1).map(p => <article className="project-row" key={p.name}><div className="project-index">{p.id}</div><div><p className="project-type">{p.type}</p><h3>{p.name}</h3></div><p>{p.description}</p><div className="row-stack">{p.stack.join(' · ')}</div><ArrowUpRight className="row-arrow" /></article>)}</div></section></Reveal>
    <Reveal><section id="lura-case" className="case-band"><div className="section-shell case-layout"><div><p className="eyebrow">LURA LAW / ENGINEERING NOTES</p><h2>From product surface<br />to <em>running system.</em></h2></div><div className="case-copy"><p>The connective tissue is the interesting part: product features, asynchronous processing, deployment and observability treated as one system.</p><div className="case-points"><span><b>01</b> OCR, documents and AI work move through background workers.</span><span><b>02</b> Terraform and Kubernetes make infrastructure repeatable.</span><span><b>03</b> Prometheus and Grafana close the feedback loop.</span></div></div></div></section></Reveal>
    <Reveal><section id="stack" className="section section-shell"><div className="section-intro compact"><span className="section-no">02</span><div><p className="eyebrow">ENGINEERING EXPERTISE</p><h2>A practical<br /><em>toolbox.</em></h2></div><p>Compact technical domains instead of a wall of badges. Tools I use to move from idea to production.</p></div><div className="expertise-tabs" role="tablist">{Object.keys(expertise).map(title => <button role="tab" aria-selected={expertiseTab === title} className={expertiseTab === title ? 'active' : ''} key={title} onClick={() => setExpertiseTab(title as keyof typeof expertise)}>{title}</button>)}</div><motion.div layout className="expertise-grid active-grid">{expertise[expertiseTab].map(x => <motion.span layout key={x}>{x}</motion.span>)}</motion.div></section></Reveal>
    <Reveal><section className="pipeline-section"><div className="section-shell pipeline-layout"><div><p className="eyebrow">DELIVERY SYSTEM</p><h2>From code<br />to <em>production.</em></h2><p>Every stage is part of the engineering surface: source, checks, containers, infrastructure and signals.</p></div><div className="pipeline-grid">{pipeline.map(([n, title, detail]) => <div className="pipeline-step" key={title}><span>{n}</span><b>{title}</b><small>{detail}</small></div>)}</div></div></section></Reveal>
    <Reveal><section id="experience" className="section section-shell"><div className="section-intro compact"><span className="section-no">03</span><div><p className="eyebrow">EXPERIENCE</p><h2>Learning by<br /><em>shipping.</em></h2></div></div><div className="experience-list">{experience.map(([year, company, role, dates, tools], i) => <button className={`experience-row ${open === i ? 'open' : ''}`} key={company} onClick={() => setOpen(open === i ? -1 : i)}><span>{year}</span><strong>{company}</strong><div><b>{role}</b><small>{dates}</small></div><ChevronDown /><p>{tools}</p></button>)}</div></section></Reveal>
    <Reveal><section id="about" className="section section-shell about"><div><p className="eyebrow">04 / ABOUT</p><h2>How I approach<br /><em>engineering.</em></h2></div><div><p className="about-lead">I build real software products and understand the infrastructure required to deliver them.</p><div className="principles">{['Build real products', 'Design for production', 'Automate repetitive work', 'Observe what you ship', 'Keep learning through building'].map((x, i) => <div key={x}><span>0{i + 1}</span><b>{x}</b></div>)}</div></div></section></Reveal>
    <section id="contact" className="contact section-shell"><div><p className="eyebrow">05 / CONTACT</p><h2>Let's build<br /><em>something useful.</em></h2></div><div><p>Open to software engineering, full-stack and cloud/DevOps opportunities.</p><div className="contact-links"><a href="mailto:amdouniwajdiii@gmail.com">EMAIL <Mail /></a><a href="https://linkedin.com/in/wajdi-amdouni">LINKEDIN <ArrowUpRight /></a><a href="https://github.com/redddFF">GITHUB <GitBranch /></a></div></div></section><footer className="section-shell footer"><b>WAJDI AMDOUNI</b><span>SOFTWARE ENGINEER · TUNISIA</span><small>© 2026</small></footer>
  </main>
}
