'use client'

import { useMemo, useState } from 'react'
import { motion, useReducedMotion, useScroll, useSpring, useTransform } from 'motion/react'
import { ArrowUpRight, Check, ChevronDown, Menu, X, Mail, Download, GitBranch, Box, Cloud, Activity } from 'lucide-react'

const stackGroups = {
  DEVELOPMENT: ['JavaScript', 'TypeScript', 'React', 'Angular', 'Vue.js', 'Next.js', 'Node.js', 'NestJS', 'Express.js', 'Spring Boot', 'Laravel'],
  CLOUD: ['Docker', 'Kubernetes', 'Helm', 'Terraform', 'Azure', 'AKS', 'DigitalOcean', 'GitHub Actions', 'Jenkins', 'GitLab'],
  INFRASTRUCTURE: ['Nginx', 'Traefik', 'GitHub OIDC', 'Infrastructure as Code', 'REST APIs', 'Microservices', 'WebSockets', 'RAG', 'Async processing'],
  DATA: ['PostgreSQL', 'MongoDB', 'MySQL', 'Oracle', 'Redis', 'Prisma', 'BullMQ', 'Prometheus', 'Grafana'],
}
const experiences = [
  { year: '2026', company: 'LURA LAW', role: 'Full Stack & DevOps Intern', dates: 'February 2026 — July 2026', tools: ['Next.js', 'NestJS', 'Azure', 'AKS', 'Terraform', 'Kubernetes', 'Redis', 'BullMQ', 'Prometheus', 'Grafana'] },
  { year: '2025', company: 'B-SMART TRAVEL', role: 'Full Stack & DevOps Intern', dates: 'February 2025 — November 2025', tools: ['React', 'Node.js', 'Docker', 'CI/CD'] },
  { year: '2024', company: 'COMUNIK CRM', role: 'Full Stack Intern', dates: 'June 2024 — August 2024', tools: ['React', 'Node.js', 'WebSockets', 'TailwindCSS'] },
  { year: '2023', company: 'VERMEG', role: 'Full Stack & DevOps Intern', dates: 'January 2023 — June 2023', tools: ['Spring Boot', 'Azure', 'CI/CD', 'Keycloak'] },
]
const architecture = [
  ['01', 'Frontend', 'Next.js', 'Product interface and workspace experience'], ['02', 'API', 'NestJS', 'Domain services and secure application logic'], ['03', 'Data', 'PostgreSQL · Prisma', 'Structured persistence and access layer'], ['04', 'Async', 'Redis · BullMQ', 'Workers for OCR, documents and AI workloads'], ['05', 'Platform', 'Terraform · Azure · AKS', 'Repeatable infrastructure and orchestration'], ['06', 'Observe', 'Prometheus · Grafana', 'Signals for understanding running systems'],
]
function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  const reduceMotion = useReducedMotion()
  const [visible, setVisible] = useState(false)
  return <motion.div className={`reveal ${visible ? 'reveal-visible' : ''} ${className}`} initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={reduceMotion ? undefined : { opacity: 1, y: 0 }} onViewportEnter={() => setVisible(true)} viewport={{ once: true, amount: 0.12 }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>
}
function ProjectCard({ name, category, description, tools, focus }: { name: string; category: string; description: string; tools: string; focus: string }) { const reduceMotion = useReducedMotion(); return <motion.article className="project-card" whileHover={reduceMotion ? undefined : { y: -8, borderColor: 'rgba(85,199,245,.55)' }} transition={{ type: 'spring', stiffness: 260, damping: 22 }}><div className="project-label">{category}</div><h3>{name}</h3><p>{description}</p><small>{tools}</small><div className="project-card-foot"><span>{focus}</span><motion.span whileHover={reduceMotion ? undefined : { x: 4 }}><ArrowUpRight size={16} /></motion.span></div></motion.article> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeStack, setActiveStack] = useState('ALL')
  const [activeArch, setActiveArch] = useState(0)
  const [openExperience, setOpenExperience] = useState(0)
  const visibleStack = useMemo(() => activeStack === 'ALL' ? Object.values(stackGroups).flat() : stackGroups[activeStack as keyof typeof stackGroups], [activeStack])
  const reduceMotion = useReducedMotion()
  const { scrollYProgress } = useScroll()
  const progress = useSpring(scrollYProgress, { stiffness: 100, damping: 30, mass: 0.2 })
  const photoY = useTransform(scrollYProgress, [0, 0.35], [0, reduceMotion ? 0 : -18])
  return <main>
    <motion.div className="top-progress" style={{ scaleX: progress, transformOrigin: '0%' }} />
    <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">WA</span><span><b>Wajdi Amdouni</b><em>Software Engineer</em></span></a><nav className={menuOpen ? 'nav-open' : ''}>{['WORK', 'EXPERIENCE', 'STACK', 'ABOUT', 'CONTACT'].map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{item}</a>)}</nav><div className="header-actions"><a href="https://github.com/redddFF" aria-label="GitHub">GH</a><a href="https://linkedin.com/in/wajdi-amdouni" aria-label="LinkedIn">IN</a><a className="resume-button" href="mailto:amdouniwajdiii@gmail.com">RESUME <Download size={13} /></a></div><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></header>
    <section id="top" className="hero section-shell"><motion.div className="hero-copy" initial={reduceMotion ? false : { opacity: 0, x: -22 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7, delay: 0.35 }}><div className="eyebrow"><span className="status-dot" /> AVAILABLE FOR OPPORTUNITIES</div><p className="kicker">FULL STACK DEVELOPMENT <span>×</span> CLOUD <span>×</span> DEVOPS</p><h1>Software<br /><i>Engineer</i></h1><p className="hero-intro">I build scalable web applications, automate infrastructure, and ship production systems from code to cloud.</p><div className="hero-ctas"><a className="button button-primary" href="#work">VIEW MY WORK <ArrowUpRight size={16} /></a><a className="button button-quiet" href="mailto:amdouniwajdiii@gmail.com">GET IN TOUCH <Mail size={15} /></a></div><a className="text-link" href="mailto:amdouniwajdiii@gmail.com">Download resume <Download size={14} /></a></motion.div><motion.div className="hero-identity" style={{ y: photoY }} initial={reduceMotion ? false : { opacity: 0, scale: 0.97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.8, delay: 0.7 }}><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/profile%20pic-LEPjak6LmAvDnqfpP1Zp0O4vlNcJ7s.jpg" alt="Portrait of Wajdi Amdouni" /><span className="identity-label identity-top">WA / SOFTWARE ENGINEER</span><span className="identity-label identity-bottom">TUNISIA · 2026</span></motion.div><motion.div className="pipeline" initial={reduceMotion ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.55 }} aria-label="Engineering delivery pipeline"><div className="pipeline-label">SYSTEM / DELIVERY_PATH <span>LIVE</span></div><div className="pipeline-line" />{[['Developer', 'Source'], ['GitHub Actions', 'CI / CD'], ['Docker', 'Container'], ['Azure · AKS', 'Cloud'], ['Production', 'Runtime']].map(([label, sub], i) => <div className={`pipeline-node n${i}`} key={label}><span className="pipeline-index">0{i + 1}</span><div className="pipeline-card"><div className="pipeline-symbol">{i === 0 ? <GitBranch /> : i === 1 ? <Activity /> : i === 2 ? <Box /> : i === 3 ? <Cloud /> : <Check />}</div><div><b>{label}</b><small>{sub}</small></div></div></div>)}<div className="pipeline-footer"><span>BUILD → DEPLOY → OBSERVE</span><span>01 / 05</span></div></motion.div><div className="meta-row"><span>BASED IN <b>TUNISIA</b></span><span>FOCUS <b>SOFTWARE ENGINEERING</b></span><span>INTEREST <b>CLOUD & DEVOPS</b></span><span>STATUS <b className="green">OPEN TO INTERNATIONAL OPPORTUNITIES</b></span></div></section>
    <Reveal><section id="work" className="section-shell section"><div className="section-heading"><span className="section-number">01</span><div><p className="eyebrow">SELECTED WORK</p><h2>Systems I&apos;ve been<br /><i>building.</i></h2></div><p className="section-note">A selection of product and platform work across full-stack development, cloud infrastructure and delivery automation.</p></div><article className="featured-project"><div className="project-copy"><div className="project-label">LEGALTECH / SAAS / CLOUD / DEVOPS</div><h3>Lura Law</h3><p>A LegalTech SaaS platform designed to help lawyers and law firms manage clients, cases, documents, deadlines, and AI-assisted legal workflows.</p><div className="tag-list">{['Next.js', 'NestJS', 'PostgreSQL', 'Redis', 'BullMQ', 'Docker', 'Terraform', 'Azure', 'AKS', 'Kubernetes', 'Prometheus', 'Grafana'].map(x => <span key={x}>{x}</span>)}</div><div className="project-links"><a href="#lura-case">VIEW CASE STUDY <ArrowUpRight size={15} /></a><span className="placeholder-link">PROJECT URL / TO BE ADDED</span></div></div><div className="architecture-card"><div className="arch-header"><span>ARCHITECTURE / LURA-LAW</span><span>INTERACTIVE MAP</span></div>{architecture.map(([num, label, tech, detail], i) => <button className={`arch-row ${activeArch === i ? 'active' : ''}`} key={num} onClick={() => setActiveArch(i)}><span className="arch-num">{num}</span><span className="arch-label">{label}</span><strong>{tech}</strong><span className="arch-detail">{activeArch === i ? detail : '↗'}</span></button>)}</div></article><div className="project-grid"><ProjectCard name="B-SMART TRAVEL" category="B2B SAAS / TRAVEL TECHNOLOGY" description="Global distribution platform for travel services with real-time booking workflows and operational tooling." tools="React · Node.js · Docker · CI/CD" focus="B2B workflows / Real-time booking" /><ProjectCard name="COMUNIK CRM" category="CRM / REAL-TIME WEB APPLICATION" description="Interactive customer management with real-time data, dynamic dashboards and activity tracking." tools="React · Node.js · WebSockets · TailwindCSS" focus="Realtime systems / Product UI" /><ProjectCard name="VERMEG DIGITAL CATALOG" category="ENTERPRISE SOFTWARE / CLOUD" description="Enterprise backend and catalog experience with role-based access, authentication and Azure delivery." tools="Spring Boot · Azure · CI/CD · Keycloak" focus="Enterprise backend / Platform" /></div></section></Reveal>
    <Reveal><section id="lura-case" className="section-shell section case-study"><div className="case-intro"><div><p className="eyebrow">LURA LAW / ENGINEERING NOTES</p><h2>From product surface<br />to <i>running system.</i></h2></div><p>The interesting part of Lura Law is the connective tissue: product features, async processing, deployment and observability treated as one system.</p></div><div className="case-timeline">{[['01', 'PRODUCT', 'LegalTech SaaS for lawyers and law firms. Authentication, workspaces, clients, cases, documents, deadlines, AI-assisted drafting, OCR and secure workflows.'], ['02', 'ASYNC PROCESSING', 'Long-running OCR, document processing and AI workloads move through Redis + BullMQ workers instead of blocking the request path.'], ['03', 'INFRASTRUCTURE', 'DigitalOcean → Azure → Terraform → Azure Resource Group → AKS → Kubernetes → Helm.'], ['04', 'CI/CD + OBSERVABILITY', 'GitHub → Actions → Build → Docker → GHCR → Deploy → AKS, with Prometheus and Grafana for system signals.']].map(([num, title, text]) => <div className="case-item" key={num}><span>{num}</span><div><b>{title}</b><p>{text}</p></div></div>)}</div></section></Reveal>
    <Reveal><section id="experience" className="section-shell section"><div className="section-heading compact"><span className="section-number">02</span><div><p className="eyebrow">ENGINEERING EXPERIENCE</p><h2>Learning by <i>shipping.</i></h2></div></div><div className="experience-list">{experiences.map((item, i) => <button className={`experience-row ${openExperience === i ? 'expanded' : ''}`} key={item.company} onClick={() => setOpenExperience(openExperience === i ? -1 : i)}><span className="exp-year">{item.year}</span><span className="exp-company">{item.company}</span><span className="exp-role">{item.role}<small>{item.dates}</small></span><ChevronDown className="exp-chevron" size={18} />{openExperience === i && <span className="exp-tools">{item.tools.map(tool => <em key={tool}>{tool}</em>)}</span>}</button>)}</div></section></Reveal>
    <Reveal><section id="stack" className="section-shell section stack-section"><div className="section-heading compact"><span className="section-number">03</span><div><p className="eyebrow">TECHNICAL STACK</p><h2>A practical <i>toolbox.</i></h2></div><p className="section-note">Tools I&apos;ve worked with while building products and learning how they behave in production.</p></div><div className="stack-filter">{['ALL', 'DEVELOPMENT', 'CLOUD', 'INFRASTRUCTURE', 'DATA'].map(filter => <button className={activeStack === filter ? 'selected' : ''} key={filter} onClick={() => setActiveStack(filter)}>{filter}</button>)}</div><div className="stack-map">{visibleStack.map((tool, i) => <span key={`${tool}-${i}`} style={{ '--delay': `${i * 25}ms` } as React.CSSProperties}>{tool}</span>)}</div></section></Reveal>
    <Reveal><section className="section-shell section lifecycle"><div className="lifecycle-copy"><p className="eyebrow">ENGINEERING MINDSET</p><h2>From code<br />to <i>production.</i></h2><p>Software is more than the interface. I&apos;m interested in the feedback loop between building, deploying, observing and improving a system.</p></div><div className="lifecycle-flow">{[['PLAN', 'Shape'], ['CODE', 'Git'], ['BUILD', 'Actions'], ['TEST', 'Checks'], ['CONTAINERIZE', 'Docker'], ['DEPLOY', 'AKS'], ['OBSERVE', 'Grafana']].map(([a, b], i) => <div className="life-node" key={a}><span>0{i + 1}</span><b>{a}</b><small>{b}</small></div>)}</div></section></Reveal>
    <Reveal><section id="about" className="section-shell section about-section"><div><p className="eyebrow">04 / ABOUT</p><h2>The space between<br />application and <i>infrastructure.</i></h2></div><div className="about-copy"><p>I&apos;m a software engineer interested in the space between application development and infrastructure.</p><p>I enjoy building products end-to-end — from designing APIs and interfaces to containerizing applications, automating deployments, provisioning cloud infrastructure, and monitoring systems in production.</p><p>My current focus is growing deeper into Cloud, Kubernetes, Infrastructure as Code, CI/CD, and platform engineering while continuing to build strong full-stack systems.</p><div className="education"><span>EDUCATION</span><div><b>Engineering Degree in Software Engineering</b><small>Higher Institute of Multimedia Arts of Manouba · 2023 — 2026</small></div><div><b>Bachelor&apos;s Degree in Information Technology</b><small>Higher Institute of Technological Studies of Bizerte · 2020 — 2023</small></div></div></div></section></Reveal>
    <Reveal><section className="section-shell section principles"><div><p className="eyebrow">HOW I BUILD</p><h2>Keep systems<br /><i>understandable.</i></h2></div><div className="principle-list">{['Build before abstracting.', 'Automate what gets repeated.', 'Infrastructure is part of the product.', 'Observability should exist before incidents.', 'Keep systems understandable.'].map((x, i) => <div key={x}><span>0{i + 1}</span><b>{x}</b></div>)}</div></section></Reveal>
    <Reveal><section id="contact" className="section-shell contact-section"><div><p className="eyebrow">05 / CONTACT</p><h2>Let&apos;s build something<br /><i>useful.</i></h2></div><div className="contact-copy"><p>Looking for software engineering, full-stack, cloud or DevOps opportunities where I can build real systems and keep learning.</p><div className="contact-actions"><a className="button button-primary" href="mailto:amdouniwajdiii@gmail.com">EMAIL ME <Mail size={16} /></a><a className="button button-quiet" href="https://linkedin.com/in/wajdi-amdouni">LINKEDIN <ArrowUpRight size={15} /></a><a className="button button-quiet" href="https://github.com/redddFF">GITHUB <GitBranch size={15} /></a></div><div className="terminal"><div className="terminal-top"><span>~/wajdi</span><span><i /> <i /> <i /></span></div><p><b>$ whoami</b>Software Engineer</p><p><b>$ focus</b>Full Stack + Cloud + DevOps</p><p><b>$ currently</b>Kubernetes / Terraform / Azure</p><p><b>$ build</b>Production-ready systems</p></div></div></section></Reveal>
    <footer className="site-footer section-shell"><div><b>Wajdi Amdouni</b><span>Software Engineer · Full Stack × Cloud × DevOps</span></div><div className="footer-status"><span className="status-dot" /> SYSTEM STATUS / ONLINE</div><div className="footer-links"><a href="https://github.com/redddFF">GitHub</a><a href="https://linkedin.com/in/wajdi-amdouni">LinkedIn</a><a href="mailto:amdouniwajdiii@gmail.com">Email</a><span>© 2026</span></div></footer>
  </main>
}
